### ISSUE TITLE
error   roslaunch mavros apm2.launch  

### ISSUE THREAD

**Issue by zpzp307** [mavlink/mavros#1236] opened 2019-05-19 13:40 UTC
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

_Please describe the problem, or desired feature_

### MAVROS version and platform

Mavros: ?0.18.4?
ROS: ?Kinetic?
Ubuntu: ?16.04?

### Autopilot type and version

[  ] ArduPilot
[  ] PX4

Version: ?3.7.1?

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
```

### Check ID

```
rosrun mavros checkid
```

**Comment by zpzp307** [comment] 2019-05-19 13:44
error loading <rosparam> tag:  	file /opt/ros/kinetic/share/mavros/launch/apm_config.yaml contains invalid YAML: while parsing a block mapping   in "<string>", line 4, column 1:     startup_px4_usb_quirk: false     ^ expected <block end>, but found '<block mapping start>'   in "<string>", line 103, column 2:      setpoint_raw:      ^ XML is <rosparam command="load" file="$(arg config_yaml)"/> The traceback for the exception was written to the log file

**Comment by TSC21** [comment] 2019-05-19 14:31
duplicate of: https://github.com/mavlink/mavros/issues/1234

**Closed by TSC21** 2019-05-19 14:31 UTC
