### ISSUE TITLE
error using mavros_msgs/RCOut

### ISSUE THREAD

**Issue by lp02781** [mavlink/mavros#956] opened 2018-02-24 08:24 UTC
i have problem when using mavros_msgs/RCOut, ubuntu 16.06, ROS kinetic adn use pixhawk. node [noFirmware.cpp] that use RCOut has died, i try to troubleshoot with comment some syntax and i know error occurs when channels out get value. if i don't give value to channels, the error doesn't occur. i need channels output to control servo. what should i do to fix that error??

thank you

> user@Lenovo:~$ roslaunch groundserver withoutFrimware.launch 
> ... logging to /home/user/.ros/log/eda29074-193a-11e8-874d-acb57df86549/roslaunch-Lenovo-6642.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://Lenovo:41010/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.12
>  * /turtle_joy/deadzone: 0.12
>  * /turtle_joy/dev: /dev/input/js0
> 
> NODES
>   /
>     identificationPlane (groundserver/identificationPlane)
>     noFirmware (groundserver/noFirmware)
>     remoteServer (groundserver/remoteServer)
>     turtle_joy (joy/joy_node)
>     videoFront (groundserver/videoFront)
> 
> auto-starting new master
> process[master]: started with pid [6652]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to eda29074-193a-11e8-874d-acb57df86549
> process[rosout-1]: started with pid [6665]
> started core service [/rosout]
> process[remoteServer-2]: started with pid [6672]
> process[noFirmware-3]: started with pid [6683]
> process[videoFront-4]: started with pid [6700]
> process[identificationPlane-5]: started with pid [6712]
> process[turtle_joy-6]: started with pid [6719]
> [noFirmware-3] process has died [pid 6683, exit code -11, cmd /home/user/Documents/kapalTenggelam/serverGabut/devel/lib/groundserver/noFirmware __name:=noFirmware __log:=/home/user/.ros/log/eda29074-193a-11e8-874d-acb57df86549/noFirmware-3.log].
> log file: /home/user/.ros/log/eda29074-193a-11e8-874d-acb57df86549/noFirmware-3*.log
> ^C[turtle_joy-6] killing on exit
> [identificationPlane-5] killing on exit
> [videoFront-4] killing on exit
> [remoteServer-2] killing on exit
> [rosout-1] killing on exit
> [master] killing on exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done
>

**Comment by TSC21** [comment] 2018-02-25 12:07
@lp02781 I don't think we will be able to help you debug your own customized ROS node this way. Also the info you provide is short to even try it. From our perspective, this is not related to MAVROS. If you, after debugging, find the problem is launched by the MAVROS node, then we can help. Closing

**Closed by TSC21** 2018-02-25 12:07 UTC
Labels: invalid, question
