### ISSUE TITLE
Build error with mavros_extras

### ISSUE THREAD

**Issue by toma-hawk** [mavlink/mavros#1426] opened 2020-05-08 04:58 UTC
Unable to Build mavros_extras package and the error is as follows:-

`Errors     << mavros_extras:make /home/okulo/catkin_ws/logs/mavros_extras/build.make.004.log
/home/okulo/catkin_ws/src/mavros/mavros_extras/src/plugins/odom.cpp: In member function ‘void mavros::extra_plugins::OdometryPlugin::odom_cb(const ConstPtr&)’:
/home/okulo/catkin_ws/src/mavros/mavros_extras/src/plugins/odom.cpp:228:53: error: ‘BODY_FRD’ is not a member of ‘mavlink::common::MAV_FRAME’
   msg.child_frame_id = utils::enum_value(MAV_FRAME::BODY_FRD);
                                                     ^~~~~~~~
make[2]: *** [CMakeFiles/mavros_extras.dir/src/plugins/odom.cpp.o] Error 1
make[1]: *** [CMakeFiles/mavros_extras.dir/all] Error 2
make: *** [all] Error 2
cd /home/okulo/catkin_ws/build/mavros_extras; catkin build --get-env mavros_extras | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << mavros_extras:make           [ Exited with code 2 ]              
Failed    <<< mavros_extras                [ 11.7 seconds ]                    
Abandoned <<< test_mavros                  [ Unrelated job failed ]            
[build] Summary: 4 of 6 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 1 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 14.7 seconds total.                `

Im using
ROS: Meloddic
Ubuntu: 18.04

**Comment by vooon** [comment] 2020-05-08 06:52
Duplicate of #1424. Please update to the latest revision.

**Closed by vooon** 2020-05-08 06:52 UTC
Labels: build error, duplicate
